# Spellcheck configuration for cargo-spellcheck

[Hunspell]
# Language setting
lang = "en_US"

# Additional dictionaries for project-specific terms
extra_dictionaries = ["dictionary.txt"]

# Where to search for dictionaries
search_dirs = ["."]

# Skip OS dictionary lookups to be more deterministic
skip_os_lookups = true