[package]
name = "bench_num"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bench_num"
path = "src/main.rs"

[dependencies]
criterion = { version = "0.7", default-features = false, features = ["cargo_bench_support"] }
num = "0.4"
